In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import ElasticNet, enet_path

In [2]:
data = pd.read_csv('/home/sasha/Data/WavePrior/data.csv', header=None)
waves = pd.read_csv('/home/sasha/Data/WavePrior/waves.csv', header=None)
lambdas = pd.read_csv('/home/sasha/Data/WavePrior/lbd.csv', header=None)

In [4]:
            DataHat{rs} = B{rs}'*wavesspeedlin +repmat(STATS{rs}.Intercept', 1, size(DataLin,1));
            SHIFT(rs,1) = r;
            diff = (DataHat{rs}'-repmat(DataLin,1,size(DataHat{rs},1)));
            RSS(rs,:) = sum((diff-repmat(mean(diff,1), size(diff,1), 1)).^2);
            Rsq(rs,:) = ones(1,size(DataHat{rs},1)) - RSS(rs,:)./TSS;
            range = range+1;
            rs = rs+1;
        end
      
        [bestRsq(s, npoint), bestshift(s, npoint)] = max(Rsq);
    end

SyntaxError: invalid syntax (<ipython-input-4-2ee928d81d66>, line 1)

In [25]:
Ndir = 6
wavelength = 6
Ns = 68
wavesspeedlin = np.empty([Ndir, Ns*wavelength])
s = 1
rs = 1
wavesspeed = waves.iloc[:,s*Ndir:(s+1)*wavelength]
for d in range(0,Ndir):
    tmp = np.array(wavesspeed.iloc[d*Ns:(d+1)*Ns,:])
    wavesspeedlin[d,:] = tmp.flatten()
R = data.shape[1] - wavelength
rng = range(0, wavelength)
r = 1
tmp = np.array(data.iloc[:,rng])
DataLin = tmp.flatten()
TSS = sum((DataLin-DataLin.mean())**2)
regr = ElasticNet(random_state=0)
regr.fit(wavesspeedlin.T, DataLin)
alphas_enet, coefs_enet, _ = enet_path(wavesspeedlin.T, 
                                       DataLin, alphas = lambdas*0.0000000001, l1_ratio=0.5, fit_intercept=True,
                                      check_input = True, positive = True)

In [26]:
coefs_enet.T

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0

In [104]:
Ndir = 6
wavelength = 6
Ns = 68
wavesspeedlin = np.empty([Ndir, Ns*wavelength])
for s in range(0, 14):
    rs = 1
    wavesspeed = waves.iloc[:,s*Ndir:(s+1)*wavelength]
    for d in range(0,Ndir):
        tmp = np.array(wavesspeed.iloc[d*Ns:(d+1)*Ns,:])
        wavesspeedlin[d,:] = tmp.flatten()
    R = data.shape[1] - wavelength
    rng = range(0, wavelength)
    for r in range(0, R):
        tmp = np.array(data.iloc[:,rng])
        DataLin = tmp.flatten()
        TSS = sum((DataLin-DataLin.mean())**2)
        regr = ElasticNet(random_state=0)
        regr.fit(wavesspeedlin.T, DataLin)
        alphas_enet, coefs_enet, _ = enet_path(wavesspeedlin.T, 
                                               DataLin, alphas = lambdas*0.01, l1_ratio=0.5, fit_intercept=True,
                                              check_input = True)
    
        
    

In [15]:
coefs_enet.T

array([[ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35642847e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35543776e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35435105e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35315721e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35184762e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.35041092e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.34883351e-09],
       [ -0.00000000e+00,  -0.00000000e+00,  -0.00000000e+00,
         -0.00000000e+00,  -0.00000000e+00,  -7.34710176e-09],


In [36]:
wavesspeedlin.T.shape

(408, 6)

In [37]:
DataLin.shape

(408,)

In [27]:
X = np.random.randint(10, size=(10, 4))

In [69]:
y = (X[:,0]+2*X[:,1]+3*X[:,2]-X[:,3])+np.random.rand(10)

In [70]:
alphas_enet, coefs_enet, _ = enet_path(X, y, l1_ratio=0.5, positive = True, fit_intercept=True,
                                          check_input = True)


In [71]:
coefs_enet.T

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.01163575,  0.05687323,  0.        ],
       [ 0.        ,  0.06118145,  0.11035081,  0.        ],
       [ 0.        ,  0.11193845,  0.16537378,  0.        ],
       [ 0.        ,  0.16381732,  0.22187674,  0.        ],
       [ 0.0391463 ,  0.21087838,  0.27492253,  0.        ],
       [ 0.07785319,  0.25745943,  0.32828269,  0.00489846],
       [ 0.11335337,  0.30013431,  0.37965111,  0.03326452],
       [ 0.14858688,  0.34265325,  0.43160685,  0.06077954],
       [ 0.18346321,  0.38492402,  0.48408735,  0.08731995],
       [ 0.2178951 ,  0.42685478,  0.5370304 ,  0.11276572],
       [ 0.25179904,  0.46835798,  0.59037555,  0.13700071],
       [ 0.28509602,  0.50935123,  0.64406439,  0.15991361],
       [ 0.31771221,  0.54975805,  0.69804094,  0.18139894],
       [ 0.34957959,  0.58950853,  0.75225175,  0.20135786],
       [ 0.3806364 ,  0.62853989,  0.80664602,  0.21969899],
       [ 0.41082757,  0.